### ISSUE TITLE
+feed/atom  results in 4 "server overload or corrupt index" tracebacks

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1017]
This occurs after using the contrib sample data to populate a wiki. Four items have invalid meta data. Each contains an invalid `parentid` field pointing to a non-existing revision. The item names are:
* png
* svg
* targz
* video4.mp4

    Traceback (most recent call last):
      File "c:\git\moin\src\moin\apps\feed\views.py", line 79, in atom
        previous_rev = item[previous_revid]
      File "c:\git\moin\src\moin\storage\middleware\protecting.py", line 412, in __getitem__
        rev = self.item[revid]
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 1090, in __getitem__
        return Revision(self, revid)
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 1241, in __init__
        doc = get_indexer(item.indexer._document, idx_name=ALL_REVS, revid=revid)
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 116, in get_indexer
        raise KeyError(kw.get('revid', '') + ' - server overload or corrupt index')
    KeyError: 'aaa98a874b7c4fa3a55fa2b3c2a6071f - server overload or corrupt index'

**Comment by ThomasWaldmann** [comment]
I just had that when requesting from http://127.0.0.1:5000/+feed/atom , so guess this is not (completely) fixed - in my case it took quite long and ran into the get_indexer timeout.

**Comment by ThomasWaldmann** [comment]
Hmm, I tried again with whoosh-reloaded and it succeeded.

So guess we need to test that again later, after we switched to whoosh-reloaded.

**Comment by UlrichB22** [comment]
I could reproduce the error:

```
moin create-instance
moin index-create
moin welcome
moin run
```

Test atom feed: http://localhost:5000/+feed/atom
Error in log:

```
  File "/home/moindev/moin/src/moin/storage/middleware/indexing.py", line 121, in get_indexer
    raise KeyError(kw.get('revid', '') + ' - server overload or corrupt index')
KeyError: '420f034d049543eaa74fe35441264a66 - server overload or corrupt index'
```

Check metadata:

```
moin maint-validate-metadata -a -v

parentid_error name: users/Home item: 39190076bdde4314a5f4d857f998a2f9 rev_number: 1 rev_id: 5df874c84981428d9f58072011e97438 meta_parentid: 420f034d049543eaa74fe35441264a66 correct_parentid: None meta_revision_number: 1
1 items with invalid metadata found

```

I will create a PR to fix users/Home meta data.

**Comment by UlrichB22** [comment]
The PR above is a proposal for discussion. 

I have renamed the function and removed the timeout handling. All situations I know of where we received the `'overload or corrupt index'` message were caused by invalid metadata. Server overload is a monitoring task for sysadmins in a production environment. Whenever it occurs, it can also affect other areas of the code.

Is this overload handling really necessary? Please give your feedback.

**Comment by RogerHaase** [comment]
I could not reproduce the error on windows using current clone, nor with UlrichB22's current branch, nor with UlrichB22's current branch with whoosh-reloaded. Will try again later.

At the point in time when get_indexer is called the current item's data has been written to the store. If get_indexer fails the index will be out of sync until the index is rebuilt. The only means of notifying the wiki admin is a message written to the log. I think the check is needed even if we cannot reproduce an overload.

iirc the last time I ran a stress load with Locust, there were no failures on Ubuntu and a few failures on Windows with heavy loads. All tests were done using the built-in server.

Whoosh also has a BufferedWriter:   https://whoosh-reloaded.readthedocs.io/en/latest/api/writing.html#utility-writers

**Comment by RogerHaase** [comment]
Tried again, cannot reproduce on Windows 10.

**Comment by UlrichB22** [comment]
I tried locust on Debian 12 and got 2 "overload" failures (with master branch). This was my setup:

```
myhost/INFO/locust.main: Starting Locust 2.24.1
myhost/INFO/locust.runners: Ramping to 8 users at a rate of 2.00 per second
myhost/INFO/locust.runners: All users spawned: {"LoadTest": 8} (8 total users) 
```
I will further analyze.

**Comment by RogerHaase** [comment]
Traceback on Windows 10 after http://[127.0.0.1:5000/+feed/atom](http://127.0.0.1:5000/+feed/atom)


    2025-09-22 12:55:28,623 ERROR moin.apps.feed.views:97 content rendering crashed on item help-common/archive.zip
    Traceback (most recent call last):
      File "C:\GIT\moin\src\moin\apps\feed\views.py", line 84, in atom
        content = hl_item.content._render_data_diff_atom(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: Binary._render_data_diff_atom() got an unexpected keyword argument 'fqname'
    2025-09-22 12:55:32,488 ERROR moin.apps.feed.views:97 content rendering crashed on item AddingSurveys/PrivateLandownerAg
    reement.doc
    Traceback (most recent call last):
      File "C:\GIT\moin\src\moin\apps\feed\views.py", line 84, in atom
        content = hl_item.content._render_data_diff_atom(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: Binary._render_data_diff_atom() got an unexpected keyword argument 'fqname'
    2025-09-22 12:55:47,283 INFO werkzeug:97 127.0.0.1 "GET /+feed/atom HTTP/1.1" 200 -

**Comment by UlrichB22** [comment]
IMO we should close this issue, as the cause of the “server overload...” errors was incorrect metadata, which has been fixed in the meantime.
Than we should create two new issues for the locust problem and this new one.

**Comment by RogerHaase** [comment]
Created new issue #1990 and fix for "unexpected keyword argument 'fqname'" above.

IMO having a server overload when running locust stress test is not an error. It shows there is a maximum load the current OS / hardware / moin software can handle and this issue can be closed as fixed with the corrected metadata.

Except that in storage/middleware/indexing.py line 115 there is  "FIXME: runs into timeout for a non-existing revid". Is that documented above or elsewhere?

And maybe indexing.py line 127 should be changed from:

    raise KeyError(kw.get("revid", "") + " - server overload or corrupt index")

to:

    raise IndexError(kw.get("revid", "") + " - server overload has corrupted the index; rebuild")

**Comment by UlrichB22** [comment]
Above PR will create different error messages for inconsistent meta data and high server load conditions.

To test the original situation from this issue I manually modified the parentid in the metadata of an old revision of an item in the filesystem, dropped and recreated the indexes.

Opening http://localhost:5000/+feed/atom results in the following traceback:

```
2025-09-27 20:54:23,506 ERROR moin.apps.feed.views:97 content rendering crashed on item Locust-JohnDoe1
Traceback (most recent call last):
  File "/home/moin2_loadtest/moin/src/moin/apps/feed/views.py", line 83, in atom
    previous_rev = item[previous_revid]
                   ~~~~^^^^^^^^^^^^^^^^
  File "/home/moin2_loadtest/moin/src/moin/storage/middleware/protecting.py", line 441, in __getitem__
    rev = self.item[revid]
          ~~~~~~~~~^^^^^^^
  File "/home/moin2_loadtest/moin/src/moin/storage/middleware/indexing.py", line 1232, in __getitem__
    return Revision(self, revid)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/moin2_loadtest/moin/src/moin/storage/middleware/indexing.py", line 1417, in __init__
    doc = get_doc(item.indexer._document, idx_name=ALL_REVS, revid=revid, retry=retry)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/moin2_loadtest/moin/src/moin/storage/middleware/indexing.py", line 127, in get_doc
    raise KeyError(msg)
KeyError: 'revid: beaf7cfc50fc4c01bdd7101bb18ce41b not found. Please check meta data and indexes'
2025-09-27 20:54:24,656 INFO werkzeug:97 127.0.0.1 "GET /+feed/atom HTTP/1.1" 200 -
```
The response takes less than a second, whereas previously it took 20 seconds or longer.
