### ISSUE TITLE
What name to use on pypi: moin or moin2

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1051]
Adding moin2 alpha/beta/rc revisions to pypi using the `moin` name seems dangerous as users may attempt to update their moin 1.9.x release.

While trying to fix #902, I changed the name in setup.py/setup_args from `moin` to `moin2`. This seemed to work well uploading alpha releases to test.pypi and downloading same into a virtualenv on both Windows and Ubuntu.

But after pushing the change to github, RTD fails:

Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/checkouts/latest/docs/conf.py", line 56, in <module>
    release = get_distribution('moin').version
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 481, in get_distribution
    dist = get_provider(dist)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 357, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'moin' distribution was not found and is required by the application

As of now the name in setup_args is back to `moin`.  Suggestions?

**Comment by ThomasWaldmann** [comment]
iirc, pip does not install non-release versions except if explicitly requested.

also, if some project or set up has a dependency on moin, they can use "moin<2.0" to avoid accidental major/incompatible upgrades even after it is released.

**Comment by RogerHaase** [comment]
OK, but still seems likely to cause some confusion to me. I cannot imagine things going well for any user trying to upgrade moin 1.9.x to moin 2.x in place. But we can try to test that and maybe fix it.

So could you add a 2.0.0a0 or so release to pypi moin so our docs and code are back in sync?

I was also thinking that we should freeze the package dependencies on the pypi release.
