### ISSUE TITLE
Build Failed for moin-2.0 on readthedocs

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1141]
Received an email from  <readthedocs@readthedocs.org>

"""
Build Failed for moin-2.0 (latest)You can find out more about this failure here:moin-2.0 build #15227637 - failedIf you have questions, a good place to start is the FAQ:https://docs.readthedocs.io/page/faq.htmlYou can unsubscribe from these emails in your Notification SettingsKeep documenting,Read the Docs | Build Failed for moin-2.0 (latest) | You can find out more about this failure here:moin-2.0 build #15227637 - failedIf you have questions, a good place to start is the FAQ:https://docs.readthedocs.io/page/faq.htmlYou can unsubscribe from these emails in your Notification Settings | Keep documenting,Read the Docs
Build Failed for moin-2.0 (latest)
You can find out more about this failure here:moin-2.0 build #15227637 - failedIf you have questions, a good place to start is the FAQ:https://docs.readthedocs.io/page/faq.htmlYou can unsubscribe from these emails in your Notification Settings
Keep documenting,Read the Docs
Read the Docshttps://readthedocs.org | Read the Docshttps://readthedocs.org
Read the Docshttps://readthedocs.org
"""

Problem is caused by docutils 0.18. Local build of docs also fails after docutils is upgraded to 0.18.:

    Traceback (most recent call last):
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\cmd\build.py", line 280, in build_main
        app.build(args.force_all, filenames)
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\application.py", line 352, in build
        self.builder.build_update()
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\builders\__init__.py", line 296, in build_update
        self.build(to_build,
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\builders\__init__.py", line 360, in build
        self.write(docnames, list(updated_docnames), method)
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\builders\__init__.py", line 534, in write
        self._write_serial(sorted(docnames))
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\builders\__init__.py", line 544, in _write_serial
        self.write_doc(docname, doctree)
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\builders\html\__init__.py", line 597, in write_doc
        self.docwriter.write(doctree, destination)
      File "c:\git\moin-venv-python\lib\site-packages\docutils\writers\__init__.py", line 78, in write
        self.translate()
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\writers\html.py", line 71, in translate
        self.document.walkabout(visitor)
      File "c:\git\moin-venv-python\lib\site-packages\docutils\nodes.py", line 199, in walkabout
        if child.walkabout(visitor):
      File "c:\git\moin-venv-python\lib\site-packages\docutils\nodes.py", line 199, in walkabout
        if child.walkabout(visitor):
      File "c:\git\moin-venv-python\lib\site-packages\docutils\nodes.py", line 191, in walkabout
        visitor.dispatch_visit(self)
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\util\docutils.py", line 468, in dispatch_visit
        method(node)
      File "c:\git\moin-venv-python\lib\site-packages\sphinx\writers\html5.py", line 356, in visit_title
        super().visit_title(node)
      File "c:\git\moin-venv-python\lib\site-packages\docutils\writers\_html_base.py", line 1661, in visit_title
        start_tag, close_tag = self.section_title_tags(node)
      File "c:\git\moin-venv-python\lib\site-packages\docutils\writers\html5_polyglot\__init__.py", line 445, in section_title_tags
        if (ids and self.settings.section_self_link
    AttributeError: 'Values' object has no attribute 'section_self_link'

After googling, suggested fix is to revert to 0.17.1

**Comment by RogerHaase** [comment]
Above patch fixed local doc builds, but build on readthedocs continues to fail.

Per https://github.com/readthedocs/readthedocs.org/issues/8616, will try creating a .readthedocs.yaml file in root:

    # see #1141 sphinx build failed with docutils==0.18

    version: 2

    python:
       install:
       - requirements: docs/requirements.txt

... and a requirements.txt file in /docs

    # see #1141 sphinx build failed with docutils==0.18
    docutils<0.18

----
The above changed the build error to:

<pre>
Running Sphinx v1.8.6

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/checkouts/latest/docs/conf.py", line 56, in <module>
    release = get_distribution('moin').version
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 471, in get_distribution
    dist = get_provider(dist)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 347, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'moin' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 201, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 203, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/moin-20/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 380, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:
</pre>
