### ISSUE TITLE
ZeroDivisionError: float division by zero after pulling recent updates

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1166]
If you pull recent changes and do not rebuild the index, you may see this traceback:

    Traceback (most recent call last):
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "c:\git\moin\src\moin\apps\frontend\views.py", line 414, in search
        name_suggestions = [word for word, score in results.key_terms(NAME, docs=20, numterms=10)]
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\searching.py", line 1273, in key_terms
        return expander.expanded_terms(numterms, normalize=normalize)
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\classify.py", line 191, in expanded_terms
        norm = model.normalizer(maxweight, self.top_total)
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\classify.py", line 62, in normalizer
        return (maxweight * log((1.0 + f) / f) + log(1.0 + f)) / log(2.0)
    ZeroDivisionError: float division by zero

Do "/m index"

**Comment by UlrichB22** [comment]
Maybe we need a function that compares timestamps and triggers an index update. The same problem occurs after updating translations, a compile_catalog is needed if the timestamp of messages.po is newer than messages.mo. Does anyone have an idea where to put these checks and if they only generate warnings in the log or trigger corrective actions directly?
