### ISSUE TITLE
traceback when search hits include an item that was uploaded

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1196]
To reproduce:

* take a moin backup
* upload the backup giving it a unique name
* search for the unique name

First failure is in frontend/views.py near line 449:

    name_suggestions = [word for word, score in results.key_terms(NAMES, docs=20, numterms=10)]

After try/except around above, second failure is in ajaxsearch.html near line 110:

    {%- if result.highlights('summary') %}
        <p class="moin-found-text">{{ _("SUMMARY: %(content)s", content=result.highlights('summary')|safe) }}</p>
    {%- endif %}

 first traceback

    Traceback (most recent call last):
      File "C:\GIT\moin-venv-python\Lib\site-packages\werkzeug\serving.py", line 323, in run_wsgi
        execute(self.server.app)
      File "C:\GIT\moin-venv-python\Lib\site-packages\werkzeug\serving.py", line 312, in execute
        application_iter = app(environ, start_response)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 2464, in __call__
        return self.wsgi_app(environ, start_response)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
        response = self.handle_exception(e)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1867, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "C:\GIT\moin\src\moin\apps\frontend\views.py", line 449, in search
        name_suggestions = [word for word, score in results.key_terms(NAMES, docs=20, numterms=10)]
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\searching.py", line 1271, in key_terms
        expander.add_document(docnum)
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\classify.py", line 146, in add_document
        self.add_text(ixreader.stored_fields(docnum).get(self.fieldname))
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\classify.py", line 159, in add_text
        self.add((from_bytes(text), weight) for text, _, weight, _
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\classify.py", line 135, in add
        for word, weight in vector:
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\classify.py", line 159, in <genexpr>
        self.add((from_bytes(text), weight) for text, _, weight, _
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\fields.py", line 156, in index
        raise ValueError("%r is not unicode or sequence" % value)
    ValueError: None is not unicode or sequence

Second traceback:

    Traceback (most recent call last):
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 2464, in __call__
        return self.wsgi_app(environ, start_response)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
        response = self.handle_exception(e)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1867, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
        response = self.full_dispatch_request()
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "C:\GIT\moin\src\moin\apps\frontend\views.py", line 481, in search
        html = render_template('search.html',
      File "C:\GIT\moin\src\moin\themes\__init__.py", line 58, in render_template
        return render_theme_template(get_current_theme(), template, **context)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask_theme\__init__.py", line 471, in render_theme_template
        return render_template(template_name, **context)
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\templating.py", line 137, in render_template
        return _render(
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\templating.py", line 120, in _render
        rv = template.render(context)
      File "C:\GIT\moin-venv-python\Lib\site-packages\jinja2\environment.py", line 1090, in render
        self.environment.handle_exception()
      File "C:\GIT\moin-venv-python\Lib\site-packages\jinja2\environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "C:\GIT\moin-venv-python\Lib\site-packages\jinja2\_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "C:\GIT\moin\src\moin\templates\search.html", line 13, in top-level template code
        {%- set search_form = None %} {# layout will not show search form in header #}
      File "C:\GIT\moin\src\moin\themes\topside\templates\layout.html", line 11, in top-level template code
        {%- import "utils.html" as utils with context %}
      File "C:\GIT\moin\src\moin\templates\base.html", line 74, in top-level template code
        {%- block layout %}
      File "C:\GIT\moin\src\moin\themes\topside\templates\layout.html", line 61, in block "layout"
        {% block item -%}
      File "C:\GIT\moin\src\moin\themes\topside\templates\layout.html", line 69, in block "item"
        {% block content %}
      File "C:\GIT\moin\src\moin\templates\search.html", line 78, in block "content"
        {%- include "ajaxsearch.html" %}
      File "C:\GIT\moin\src\moin\templates\ajaxsearch.html", line 113, in top-level template code
        {%- if result.highlights('summary') %}
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\searching.py", line 1452, in highlights
        return hliter.highlight_hit(self, fieldname, text=text, top=top,
      File "C:\GIT\moin-venv-python\Lib\site-packages\whoosh\highlight.py", line 904, in highlight_hit
        raise KeyError("Field %r is not stored." % fieldname)
    KeyError: "Field 'summary' is not stored."

**Comment by RogerHaase** [comment]
Problem 1 is that the SUMMARY field is not set in meta data when a file is uploaded. The summary field can be set to "" as a default. The user must use Modify to set Comment, ACL, Summary or Tags metadata and must use Rename to change the uploaded file name.

Problem 2 is that the NAMES field is not set when an item is deleted. The field can be set to "" as a default that will prevent deleted items from being searched by name; or the NAMES field can be set based upon OLD_NAME to allow deleted items to be searched by name.

Problem 3 is that fixing the above does not correct the metadata for past uploads/deletes that early moin2 adopters may have in their wikis. Wiki admins will have to fix, re-upload files, and restore / delete items.
