### ISSUE TITLE
Babel 2.10.1 breaks quickinstall.py

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1239]
From the log:

    --- Logging error ---
    Traceback (most recent call last):
      File "C:\Users\haase\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
        stream.write(msg + self.terminator)
    ValueError: underlying buffer has been detached
    Call stack:
      File "C:\GIT\moin\setup.py", line 140, in <module>
        setup(**setup_args)
      File "C:\GIT\moin-venv-python\lib\site-packages\setuptools\__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "C:\GIT\moin-venv-python\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
        return run_commands(dist)
      File "C:\GIT\moin-venv-python\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
        dist.run_commands()
      File "C:\GIT\moin-venv-python\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "C:\GIT\moin-venv-python\lib\site-packages\setuptools\dist.py", line 1214, in run_command
        super().run_command(command)
      File "C:\GIT\moin-venv-python\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
        cmd_obj.run()
      File "C:\GIT\moin-venv-python\lib\site-packages\babel\messages\frontend.py", line 193, in run
        for catalog, errors in self._run_domain(domain).items():
      File "C:\GIT\moin-venv-python\lib\site-packages\babel\messages\frontend.py", line 264, in _run_domain
        self.log.info('compiling catalog %s to %s', po_file, mo_file)
    Message: 'compiling catalog %s to %s'
    Arguments: ('C:\\git\\moin\\src\\moin\\translations\\de\\LC_MESSAGES\\messages.po', 'C:\\git\\moin\\src\\moin\\translations\\de\\LC_MESSAGES\\messages.mo')

**Comment by JanHoefelmeyer** [comment]
Has this been fixed by the mentioned pull requests? Cannot replicate this issue on the current branch anymore.

**Comment by RogerHaase** [comment]
Not fixed. To fix the workaround code above in setup.py must be reverted:

        <snip>
        'Babel==2.9.1',  # Babel 2.10.1 breaks quickinstall.py #1239
        <snip>
        'docutils<0.18',  # reST markup processing, see #1141 build fails with 0.18; sphinx 4.3.0 requires docutils<0.18,>=0.14,
        <snip>

* remove  babel line
* set docutils >= ?

See #1240, the sphinx-rtd-theme may need an update, 

Testing requires building local docs (./m docs) and running an update to read-the-docs successfully. #1141

**Comment by UlrichB22** [comment]
This is fixed with #1338.

My latest tests with ./m docs were using
- Babel                         2.10.3
- docutils                      0.18.1
- sphinx                        6.1.3
- sphinx-rtd-theme              1.2.0rc3

**Comment by UlrichB22** [comment]
sphinx-rtd-theme stable version 1.2.0 is released since 07.02.2023.
Todays Readthedocs build finished successfully using 
- docutils-0.18.1 
- sphinx-6.1.3 
- sphinx-rtd-theme-1.2.0
