### ISSUE TITLE
moin and moin help commands fail without valid wiki

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1270]
The commands `moin` and `moin help` fail when they are issued outside of a valid wiki root directory.

Running moin in a directory without wiki instance but with wikiconfig.py (typically after fresh sw install) gives:
 
```
Traceback (most recent call last):
  File "/home/mointst/test/moin-venv-python3/bin/moin", line 33, in <module>
    sys.exit(load_entry_point('moin', 'console_scripts', 'moin')())
  File "/home/mointst/test/moin/src/moin/scripts/__init__.py", line 95, in main
    return manager.run(default_command=default_command)
  File "/home/mointst/test/moin-venv-python3/lib/python3.9/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/home/mointst/test/moin-venv-python3/lib/python3.9/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/home/mointst/test/moin-venv-python3/lib/python3.9/site-packages/flask_script/__init__.py", line 159, in __call__
    app = app(**kwargs)
  File "/home/mointst/test/moin/src/moin/app.py", line 52, in create_app
    return create_app_ext(flask_config_file=config,
  File "/home/mointst/test/moin/src/moin/app.py", line 158, in create_app_ext
    init_backends(app)
  File "/home/mointst/test/moin/src/moin/app.py", line 199, in init_backends
    app.storage.open()
  File "/home/mointst/test/moin/src/moin/storage/middleware/indexing.py", line 539, in open
    self.ix[name] = storage.open_index(name)
  File "/home/mointst/test/moin-venv-python3/lib/python3.9/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/home/mointst/test/moin-venv-python3/lib/python3.9/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/home/mointst/test/moin-venv-python3/lib/python3.9/site-packages/whoosh/index.py", line 618, in read
    raise EmptyIndexError("Index %r does not exist in %r"
whoosh.index.EmptyIndexError: Index 'latest_revs' does not exist in FileStorage('/home/mointst/test/moin/wiki/index')
2022-06-19 19:25:21,153 WARNING moin.utils.clock:52 These timers have not been stopped: create_app total, create_app init backends
```

In an directory without wikiconfig (e.g. /tmp) the error is different:

```
moin.error.ConfigurationError: No storage configuration specified! You need to define a namespace_mapping.
2022-06-19 19:29:38,762 WARNING moin.utils.clock:52 These timers have not been stopped: create_app total, create_app load config

```
As an initial help these commands should always run without problems.

**Comment by UlrichB22** [comment]
No idea how to solve the `moin` without subcommand easily.
