### ISSUE TITLE
Script 'moin account-create' fails with AttributeError

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1343]
The command `moin account-disable --name testuser01`  fails with following Traceback:

```
 ad0e62605c2c4b45ac3817e62069742f ['testuser01']            test11@user.domain                  Traceback (most recent call last):
  File "/home/moint02/test/moin-venv-python3/bin/moin", line 33, in <module>
    sys.exit(load_entry_point('moin', 'console_scripts', 'moin')())
  File "/home/moint02/test/moin/src/moin/scripts/__init__.py", line 93, in main
    return manager.run(default_command=default_command)
  File "/home/moint02/test/moin-venv-python3/lib/python3.9/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/moint02/test/moin-venv-python3/lib/python3.9/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/moint02/test/moin-venv-python3/lib/python3.9/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/home/moint02/test/moin/src/moin/scripts/account/disable.py", line 45, in run
    u.name = "{0}-{1}".format(u.name, u.id)
  File "/home/moint02/test/moin/src/moin/user.py", line 368, in __getattr__
    raise AttributeError(name)
AttributeError: id

```

**Comment by UlrichB22** [comment]
There is some logic to add the uid/itemid to the username and email:
https://github.com/moinwiki/moin/blob/80844fa31b432cca7220fb98b3c3bc29340fa28d/src/moin/scripts/account/disable.py#L45

This code has been adopted from moin1.9. Disabling a user using the frontend does not follow this logic. I would like to remove these lines of code, please advise. I am actually working on the migration from flask-script to click.

**Comment by RogerHaase** [comment]
Agree it seems wrong to mangle the email and user name so OK to remove the lines of code doing that.

After fixing that, the save doesn't work, user metadata is not updated.
