### ISSUE TITLE
moin save / moin load yields traceback

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1402]
To reproduce create a new wiki, load help-en, take a backup, delete wiki, create an empty wiki, load backup.

Problem only occurs when help-en is loaded.

    moin load-help -n en
    moin save -f wiki/mybackup.moin -a true
    moin load -f wiki/mybackup.moin

8 help-en files are loaded, then:

    (moin-venv-python) C:\git\moin>moin load --file wiki/myback.moin
    2023-04-13 14:16:42,510 INFO moin.cli.maint.serialization:93 Load backup started
    Traceback (most recent call last):
      File "C:\GIT\moin-venv-python\Scripts\moin-script.py", line 33, in <module>
        sys.exit(load_entry_point('moin', 'console_scripts', 'moin')())
      File "C:\GIT\moin-venv-python\lib\site-packages\click\core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
      File "C:\GIT\moin-venv-python\lib\site-packages\flask\cli.py", line 601, in main
        return super().main(*args, **kwargs)
      File "C:\GIT\moin-venv-python\lib\site-packages\click\core.py", line 1055, in main
        rv = self.invoke(ctx)
      File "C:\GIT\moin-venv-python\lib\site-packages\click\core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "C:\GIT\moin-venv-python\lib\site-packages\click\core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "C:\GIT\moin-venv-python\lib\site-packages\click\core.py", line 760, in invoke
        return __callback(*args, **kwargs)
      File "C:\GIT\moin-venv-python\lib\site-packages\click\decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
      File "C:\GIT\moin-venv-python\lib\site-packages\flask\cli.py", line 445, in decorator
        return __ctx.invoke(f, *args, **kwargs)
      File "C:\GIT\moin-venv-python\lib\site-packages\click\core.py", line 760, in invoke
        return __callback(*args, **kwargs)
      File "c:\git\moin\src\moin\cli\maint\serialization.py", line 95, in Deserialize
        deserialize(f, app.storage.backend, new_ns=new_ns, old_ns=old_ns, kill_ns=kill_ns)
      File "c:\git\moin\src\moin\storage\middleware\serialization.py", line 77, in deserialize
        text = meta_str.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 9065: invalid start byte

**Comment by RogerHaase** [comment]
Traceback caused by 4 help-en meta files with invalid size data:

|filename|meta size|file size| 
|-----|----|----|
|WikiDict|615|613|
|TemplateSample|896|891|
|rst|21399|21376|
|OtherTextItems/Diff|2242|2254|

Looks like the problem was introduced with initial load of help/en data.

Workaround: do not backup help files. 
* `m backup`  does backup help files, no option to not backup help files
* `moin save -b default -f <filename>` does not backup help files

**Comment by bylsmad** [comment]
@RogerHaase   would it help to add a test for this bug?  let me know I can put up a pull req with an xfail test if you like.

**Comment by UlrichB22** [comment]
IMO we should have a function to check meta data consistency similar to http://localhost:5000/+orphans and http://localhost:5000/+wanteds. This can be a CLI command, because it can have a longer runtime depending on the size of the wiki. Maybe it can be added to the save command with a new option. Things to check can be
- Size
- Parent Revision ID
- Revision Number
- ...

**Comment by RogerHaase** [comment]
@bylsmad would be a good idea to add test as well

**Comment by bylsmad** [comment]
I've added a test with an xfail for the situation before PR #1413

Strangely, the save -a / load test is passing on Linux, failing on windows with a utf-8 error, the xfail fails on all OS

branch: https://github.com/bylsmad/moin/tree/1387-cli-test-save-restore
test run: https://github.com/bylsmad/moin/actions/runs/4776684140

**Comment by bylsmad** [comment]
whatever is done to allow for fixing bad metadata IMO it should be done automatically during `moin save` to prevent creating unusable backups...even if we prevent bad sizes from entering as they can now via `moin load-help` there is always the possibility an admin could edit their data files outside of moin and create this situation which could lead to an unrecoverable wiki

**Comment by bylsmad** [comment]
just discovered the reason why load-help allows the bad metadata into storage, it is the overwrite

I've added a couple commits to the branch in my fork.  The github action now archives the backups created in test_serialization.  I downloaded the backups created in the windows run to my Linux workstation and was able to `moin load` them with no issue, so whatever is causing the failure on windows I'm thinking it has to do with the load, not the save operation

**Comment by bylsmad** [comment]
I believe the issue is with help/common/logo.svg - looks like git sees it as a text file so it converts the line endings to windows on the build host which uses autocrlf=true ... because the content-type in the meta file is "contenttype": "image/svg+xml", moin does not see it as text so it does not do the line ending conversion during load-help on Linux nor on windows machines with autocrlf=input  ... if we implement the "fix the metadata on save" then this should be fixed...this evening I will pretty up my test branch and add xfail for windows for the test_load_all and put up a pull req

**Comment by bylsmad** [comment]
ok got the tests behaving correctly in all envs PR #1418

**Comment by RogerHaase** [comment]
Something I have not seen before. On merge tests for Macos and Ubuntu OK, Windows failed:

https://github.com/moinwiki/moin/actions/runs/4962917141

Local tests on windows 10 OK.

**Comment by bylsmad** [comment]
looks like test_Macro is asserting dates are equal in minutes, and this test run was unlucky enough to run just as the time switched from 1:06 to 1:07.
best fix would be to have the test parse the return from the macro back into a datetime and assert that the difference between test_time and result is less than timedelta(seconds=1)
I'm heading out for a hike today so the earliest I could put this in would be tomorrow.
-David    On Saturday, May 13, 2023 at 07:07:49 AM PDT, RogerHaase ***@***.***> wrote:  
 
 


Something I have not seen before. On merge tests for Macos and Ubuntu OK, Windows failed:

https://github.com/moinwiki/moin/actions/runs/4962917141

Local tests on windows 10 OK.
