### ISSUE TITLE
dump-html optimization

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1452]
I tested `moin dump-html` command after creating a new instance with `moin create-instance --full` .

The following might be optimized:

-  wiki links inside the items are invalid, not pointing to the encoded item names 

-  there are three items 'Home' found as home page because namespace is ignored, in my case the content in `HTML/Home.html` is from `users/Home`

-  Slashes are encoded with '(2f)'

**Comment by RogerHaase** [comment]
I did not create a new instance, but ran `m dump-html` from my repo. Within the HTML directory, the file Home has correct links but _Home and Home.html has bad links. 

Within the m-dump-html.txt log file there was a traceback. iirc this has alway been there and is harmless (but I am not sure).

    Traceback (most recent call last):
      File "c:\git-ulrichb22\moin\src\moin\converters\macro.py", line 55, in handle_macro
        ret = macro((), args, page, alt, context_block)
      File "c:\git-ulrichb22\moin\src\moin\macros\_base.py", line 56, in __call__
        ret = self.macro(content, arguments, page_url, alternative)
      File "c:\git-ulrichb22\moin\src\moin\macros\MailTo.py", line 27, in macro
        assert len(arguments) > 0 and len(arguments) < 3
    TypeError: object of type 'NoneType' has no len()

**Comment by UlrichB22** [comment]
Thanks for review. I can have a look at the MailTo macro later. 

One minor issue left are links with an anchor. They don't match the replace functions. No idea how to add that efficiently.

**Comment by UlrichB22** [comment]
Can reproduce the traceback `TypeError: object of type 'NoneType' has no len()`
when using the MailTo macro without arguments: `<<MailTo()>>`

**Comment by UlrichB22** [comment]
dump-html fails if a user exists:

```
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/moin-2.0.0.dev1441+g2a987814.d20230521-py3.9.egg/moin/cli/maint/dump_html.py", line 151, in Dump
    used_dirs = get_used_dirs(query=q)
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/moin-2.0.0.dev1441+g2a987814.d20230521-py3.9.egg/moin/cli/maint/dump_html.py", line 280, in get_used_dirs
    dirs, files = item.make_flat_index(revs, True)
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/moin-2.0.0.dev1441+g2a987814.d20230521-py3.9.egg/moin/items/__init__.py", line 1083, in make_flat_index
    mini_meta = {key: rev[key] for key in (CONTENTTYPE, ITEMTYPE, SIZE, MTIME, REV_NUMBER, NAMESPACE)}
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/moin-2.0.0.dev1441+g2a987814.d20230521-py3.9.egg/moin/items/__init__.py", line 1083, in <dictcomp>
    mini_meta = {key: rev[key] for key in (CONTENTTYPE, ITEMTYPE, SIZE, MTIME, REV_NUMBER, NAMESPACE)}
KeyError: 'itemtype'
```
make_flat_index fails because meta data in userprofiles don't have ITEMTYPE.
