### ISSUE TITLE
traceback running quickinstall.py

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1495]
Possibly caused by recent updates to setuptools, werkzeug, or click. But unable to workaround traceback by forcing earlier versions.

|package|prior version|current version|
|-----|-----:|-----:|
|setuptools|68.0.0|68.1.2|
|werkzeug|2.3.6|2.3.7|
|click|8.1.6|8.1.7|

        Traceback (most recent call last):
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\util.py", line 212, in subst_vars
            return _subst_compat(s).format_map(lookup)
        KeyError: 'GIT'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:\$GIT\moin2\moin\setup.py", line 137, in <module>
            setup(**setup_args)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
            return run_commands(dist)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
            dist.run_commands()
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\dist.py", line 1233, in run_command
            super().run_command(command)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
            cmd_obj.ensure_finalized()
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
            self.finalize_options()
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\command\develop.py", line 50, in finalize_options
            easy_install.finalize_options(self)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\command\easy_install.py", line 290, in finalize_options
            self._expand(
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\command\easy_install.py", line 1389, in _expand
            config_vars = self.get_finalized_command('install').config_vars
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
            cmd_obj.ensure_finalized()
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
            self.finalize_options()
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\command\install.py", line 55, in finalize_options
            orig.install.finalize_options(self)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\command\install.py", line 439, in finalize_options
            self.expand_basedirs()
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\command\install.py", line 619, in expand_basedirs
            self._expand_attrs(['install_base', 'install_platbase', 'root'])
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\command\install.py", line 613, in _expand_attrs
            val = subst_vars(val, self.config_vars)
          File "C:\$GIT\moin2\moin-venv-python\lib\site-packages\setuptools\_distutils\util.py", line 214, in subst_vars
            raise ValueError(f"invalid variable {var}")
        ValueError: invalid variable 'GIT'
        [end of output]

**Comment by RogerHaase** [comment]
User error - moin or setuptools creates above error when there is a $GIT in the filename path, where $ is the offending character.
