### ISSUE TITLE
fix-test-time-zones - use more conventional time zone names

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1510]
Issue raised on the moin-devel mailing list by Paul B.:

I think it is something to do with the kind of time zone involved. US/Arizona 
is some kind of alias, whereas America/Phoenix is one of the fundamental 
zones. For some reason, in the package build environment, the pytz 
configuration doesn't recognise the alias whereas it does generally.

It seems to be something that pytz in Debian unstable does not support:

```
import pytz
pytz.timezone("US/Arizona")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pytz/__init__.py", line 200, in 
timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'US/Arizona'

```
Looking further, it appears that pytz may be provided as some kind of wrapper 
around the zoneinfo module:

https://packages.debian.org/sid/python3-pytz-deprecation-shim

So, I guess this is yet another Python ecosystem regression.

**Comment by UlrichB22** [comment]
The fix can be found here:
https://salsa.debian.org/moin-team/moin/-/blob/debian/master/debian/patches/015-fix-test-time-zones
