### ISSUE TITLE
CI workflow and ./m quickinstall failing to write _version.py

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1515]
Getting following error with `./m quickinstall`

```
py39: packaging backend failed (code=1), with AssertionError: write_to=PosixPath('/home/moint03/test/moin/src/moin/_version.py')
/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'message_extractors'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/pyproject_api/_backend.py", line 90, in run
    outcome = backend_proxy(parsed_message["cmd"], **parsed_message["kwargs"])
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/pyproject_api/_backend.py", line 32, in __call__
    return getattr(on_object, name)(*args, **kwargs)
  File "/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
    self.run_setup()
[...]
  File "/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 102, in version_keyword
    _assign_version(dist, config)
  File "/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 54, in _assign_version
    maybe_version = _get_version(config, force_write_version_files=True)
  File "/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 94, in _get_version
    write_version_files(config, version=version_string, scm_version=parsed_version)
  File "/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 63, in write_version_files
    dump_version(
  File "/home/moint03/test/moin/.tox/.pkg/lib/python3.9/site-packages/setuptools_scm/_integration/dump_version.py", line 36, in dump_version
    assert not write_to.is_absolute(), f"{write_to=}"
AssertionError: write_to=PosixPath('/home/moint03/test/moin/src/moin/_version.py')

```

**Comment by ThomasWaldmann** [comment]
Can you try a not absolute path for that, like:
```
write_to = "src/moin/_version.py"
```

**Comment by wagner-intevation** [comment]
Isn't that the case already?
https://github.com/moinwiki/moin/blob/a1147ae28483453e2febacb8cc6a94bf39a7893a/setup.py#L10
https://github.com/moinwiki/moin/blob/a1147ae28483453e2febacb8cc6a94bf39a7893a/setup.py#L67-L69

**Comment by ThomasWaldmann** [comment]
No, basedir **is** an absolute path.

**Comment by UlrichB22** [comment]
setuptools_scm has been raised to 8.0.0 and 8.0.1 today. 
The workaround switches back to the latest successful setup. 
Lets wait some time before reverting.

**Comment by ThomasWaldmann** [comment]
https://github.com/pypa/setuptools_scm/blob/main/src/setuptools_scm/_integration/dump_version.py#L38

It specifically does not allow an absolute path there.

I just tried the latest setuptools_scm in borgbackup master branch (we also use write_to there, but with a relative path) and it worked.

**Comment by UlrichB22** [comment]
setuptools_scm 8.0.3 now accepts absolut path again but issues a deprecated warning, see 
https://github.com/pypa/setuptools_scm/issues/925
