### ISSUE TITLE
HTTP error 500 when clicking preview on a newly created item

### ISSUE THREAD

**Issue by UlrichB22** [moinwiki/moin#1539]
When you click on 'preview' for a newly created item of type PDF before uploading a file you get an HTTP error 500. Likely the same problem will happen for all other non-markup content-types. This is the traceback in the server log:

```
2023-10-02 18:25:12,654 ERROR moin.signalling.log:30 'NoneType' object has no attribute 'splitlines'
Traceback (most recent call last):
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/moint03/test/moin/src/moin/apps/frontend/views.py", line 798, in modify_item
    ret = item.do_modify()
  File "/home/moint03/test/moin/src/moin/items/__init__.py", line 1340, in do_modify
    preview_diffs = [(d[0], Markup(d[1]), d[2], Markup(d[3])) for d in html_diff(old_text, data)]
  File "/home/moint03/test/moin/src/moin/utils/diff_html.py", line 36, in diff
    seq2 = new.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
2023-10-02 18:25:12,658 ERROR moin:1744 Exception on /+modify/testNew3 [POST]
Traceback (most recent call last):
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moint03/test/moin-venv-python3/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/moint03/test/moin/src/moin/apps/frontend/views.py", line 798, in modify_item
    ret = item.do_modify()
  File "/home/moint03/test/moin/src/moin/items/__init__.py", line 1340, in do_modify
    preview_diffs = [(d[0], Markup(d[1]), d[2], Markup(d[3])) for d in html_diff(old_text, data)]
  File "/home/moint03/test/moin/src/moin/utils/diff_html.py", line 36, in diff
    seq2 = new.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'
2023-10-02 18:25:12,661 INFO werkzeug:187 127.0.0.1 "POST /+modify/testNew3?itemtype=default&contenttype=application/pdf&template= HTTP/1.1" 500 -
```

**Comment by UlrichB22** [comment]
In addition to the fix in #1553, the Preview button should be disabled if it is not applicable.
