### ISSUE TITLE
CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'

### ISSUE THREAD

**Issue by sebix** [moinwiki/moin#1788]
Running on master (0ec608c6dd4210bc20f752984a8217ba5edbf62e) I get this huge error message for every page:

```
 * Debug mode: off
2024-10-27 19:39:30,418 INFO werkzeug:97 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
2024-10-27 19:39:30,418 INFO werkzeug:97 Press CTRL+C to quit
2024-10-27 19:39:35,255 INFO moin.signalling.log:20 item MyMoinMoin:Home displayed
2024-10-27 19:39:35,576 ERROR moin.signalling.log:31 CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'
Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 472, in render_theme_template
    return render_template('_themes/%s/%s' % (theme, template_name),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/loaders.py", line 578, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: _themes/modernized/show.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/apps/frontend/views.py", line 595, in show_item
    result = item.do_show(rev, item_is_deleted=item_is_deleted, item_may=item_may)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/items/__init__.py", line 1453, in do_show
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 70, in render_template
    return render_theme_template(get_current_theme(), template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 476, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/dev/moin/src/moin/templates/show.html", line 7, in top-level template code
    {% set footer_meta = snippets.footer_meta() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 13, in top-level template code
    {% set creditlogos = snippets.creditlogos() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/base.html", line 74, in top-level template code
    {%- block layout %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 20, in block 'layout'
    {% block header %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 37, in block 'header'
    {{ utils.breadcrumbs(theme_supp.path_breadcrumbs, title_name) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/utils.html", line 258, in template
    {%- set trail_items = breadcrumbs() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 365, in path_breadcrumbs
    trail = user.get_trail()
            ^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in get_trail
    aliases = [CompositeName(*alias) for alias in entry[1]]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in <listcomp>
    aliases = [CompositeName(*alias) for alias in entry[1]]
               ^^^^^^^^^^^^^^^^^^^^^
TypeError: CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'
2024-10-27 19:39:35,578 ERROR moin:838 Exception on /Home [GET]
Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 472, in render_theme_template
    return render_template('_themes/%s/%s' % (theme, template_name),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/loaders.py", line 578, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: _themes/modernized/show.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/apps/frontend/views.py", line 595, in show_item
    result = item.do_show(rev, item_is_deleted=item_is_deleted, item_may=item_may)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/items/__init__.py", line 1453, in do_show
    return render_template(
           ^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 70, in render_template
    return render_theme_template(get_current_theme(), template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 476, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/dev/moin/src/moin/templates/show.html", line 7, in top-level template code
    {% set footer_meta = snippets.footer_meta() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 13, in top-level template code
    {% set creditlogos = snippets.creditlogos() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/base.html", line 74, in top-level template code
    {%- block layout %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 20, in block 'layout'
    {% block header %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 37, in block 'header'
    {{ utils.breadcrumbs(theme_supp.path_breadcrumbs, title_name) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/utils.html", line 258, in template
    {%- set trail_items = breadcrumbs() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 365, in path_breadcrumbs
    trail = user.get_trail()
            ^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in get_trail
    aliases = [CompositeName(*alias) for alias in entry[1]]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in <listcomp>
    aliases = [CompositeName(*alias) for alias in entry[1]]
               ^^^^^^^^^^^^^^^^^^^^^
TypeError: CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'
2024-10-27 19:39:35,580 INFO werkzeug:97 127.0.0.1 "GET /Home HTTP/1.1" 500 -
2024-10-27 19:39:35,794 INFO moin.signalling.log:20 item MyMoinMoin:favicon.ico displayed
2024-10-27 19:39:35,860 ERROR moin.signalling.log:31 CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'
Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 472, in render_theme_template
    return render_template('_themes/%s/%s' % (theme, template_name),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/loaders.py", line 578, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: _themes/modernized/show_nonexistent.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/apps/frontend/views.py", line 595, in show_item
    result = item.do_show(rev, item_is_deleted=item_is_deleted, item_may=item_may)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/items/__init__.py", line 1777, in do_show
    content = render_template("show_nonexistent.html", item_name=self.name, fqname=self.fqname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 70, in render_template
    return render_theme_template(get_current_theme(), template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 476, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/dev/moin/src/moin/templates/show_nonexistent.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 13, in top-level template code
    {% set creditlogos = snippets.creditlogos() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/base.html", line 74, in top-level template code
    {%- block layout %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 20, in block 'layout'
    {% block header %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 37, in block 'header'
    {{ utils.breadcrumbs(theme_supp.path_breadcrumbs, title_name) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/utils.html", line 258, in template
    {%- set trail_items = breadcrumbs() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 365, in path_breadcrumbs
    trail = user.get_trail()
            ^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in get_trail
    aliases = [CompositeName(*alias) for alias in entry[1]]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in <listcomp>
    aliases = [CompositeName(*alias) for alias in entry[1]]
               ^^^^^^^^^^^^^^^^^^^^^
TypeError: CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'
2024-10-27 19:39:35,861 ERROR moin:838 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 472, in render_theme_template
    return render_template('_themes/%s/%s' % (theme, template_name),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/loaders.py", line 578, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: _themes/modernized/show_nonexistent.html

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/apps/frontend/views.py", line 595, in show_item
    result = item.do_show(rev, item_is_deleted=item_is_deleted, item_may=item_may)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/items/__init__.py", line 1777, in do_show
    content = render_template("show_nonexistent.html", item_name=self.name, fqname=self.fqname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 70, in render_template
    return render_theme_template(get_current_theme(), template, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask_theme/__init__.py", line 476, in render_theme_template
    return render_template(template_name, **context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/user/dev/moin/src/moin/templates/show_nonexistent.html", line 1, in top-level template code
    {% extends theme("layout.html") %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 13, in top-level template code
    {% set creditlogos = snippets.creditlogos() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/base.html", line 74, in top-level template code
    {%- block layout %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 20, in block 'layout'
    {% block header %}
  File "/home/user/dev/moin/src/moin/templates/layout.html", line 37, in block 'header'
    {{ utils.breadcrumbs(theme_supp.path_breadcrumbs, title_name) }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin-venv-python/lib64/python3.11/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/templates/utils.html", line 258, in template
    {%- set trail_items = breadcrumbs() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/themes/__init__.py", line 365, in path_breadcrumbs
    trail = user.get_trail()
            ^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in get_trail
    aliases = [CompositeName(*alias) for alias in entry[1]]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/dev/moin/src/moin/user.py", line 765, in <listcomp>
    aliases = [CompositeName(*alias) for alias in entry[1]]
               ^^^^^^^^^^^^^^^^^^^^^
TypeError: CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'
2024-10-27 19:39:35,863 INFO werkzeug:97 127.0.0.1 "GET /favicon.ico HTTP/1.1" 500 -
```

**Comment by UlrichB22** [comment]
I cannot reproduce. can you please clear the browser history and retry?

**Comment by sebix** [comment]
The cause appears to be a cookie from the previous commit, you are right.

I wouldn't have expected a server error in such cases, to be honest.
