### ISSUE TITLE
traceback processing page trail

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#1801]
Traceback (most recent call last):
      File "C:\GIT\moin-venv-python\Lib\site-packages\werkzeug\serving.py", line 370, in run_wsgi
        execute(self.server.app)
      File "C:\GIT\moin-venv-python\Lib\site-packages\werkzeug\serving.py", line 331, in execute
        application_iter = app(environ, start_response)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1498, in __call__
        return self.wsgi_app(environ, start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
        response = self.handle_exception(e)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
        response = self.full_dispatch_request()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
        rv = self.handle_user_exception(e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
        rv = self.dispatch_request()
             ^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\app.py", line 865, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin\src\moin\apps\frontend\views.py", line 595, in show_item
        result = item.do_show(rev, item_is_deleted=item_is_deleted, item_may=item_may)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin\src\moin\items\__init__.py", line 1453, in do_show
        return render_template(
               ^^^^^^^^^^^^^^^^
      File "C:\GIT\moin\src\moin\themes\__init__.py", line 70, in render_template
        return render_theme_template(get_current_theme(), template, **context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask_theme\__init__.py", line 476, in render_theme_template
        return render_template(template_name, **context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\templating.py", line 150, in render_template
        return _render(app, template, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\flask\templating.py", line 131, in _render
        rv = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin-venv-python\Lib\site-packages\jinja2\environment.py", line 1304, in render
        self.environment.handle_exception()
      File "C:\GIT\moin-venv-python\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "C:\GIT\moin\src\moin\templates\show.html", line 7, in top-level template code
        {% set footer_meta = snippets.footer_meta() %}
      File "C:\GIT\moin\src\moin\themes\topside\templates\layout.html", line 11, in top-level template code
        {%- import "utils.html" as utils with context %}
      File "C:\GIT\moin\src\moin\templates\base.html", line 74, in top-level template code
        {%- block layout %}
      File "C:\GIT\moin\src\moin\themes\topside\templates\layout.html", line 18, in block 'layout'
        {%- block header %}
      File "C:\GIT\moin\src\moin\themes\topside\templates\layout.html", line 53, in block 'header'
        {{ utils.breadcrumbs(theme_supp.path_breadcrumbs, title_name) }}
      File "C:\GIT\moin-venv-python\Lib\site-packages\jinja2\runtime.py", line 782, in _invoke
        rv = self._func(*arguments)
             ^^^^^^^^^^^^^^^^^^^^^^
      File "C:\GIT\moin\src\moin\templates\utils.html", line 258, in template
        {%- set trail_items = breadcrumbs() %}
      File "C:\GIT\moin\src\moin\themes\__init__.py", line 365, in path_breadcrumbs
        trail = user.get_trail()
                ^^^^^^^^^^^^^^^^
      File "C:\GIT\moin\src\moin\user.py", line 765, in get_trail
        aliases = [CompositeName(*alias) for alias in entry[1]]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: CompositeName.__new__() missing 2 required positional arguments: 'field' and 'value'

**Comment by UlrichB22** [comment]
I will try to make the page trail fault-tolerant. 
Is this issue reproducible?

**Comment by RogerHaase** [comment]
Was repeatable across multiple browsers right after login. Problem went away just now when I deleted cookies for 127.0.0.1:5000.

Maybe do nothing other than leave this open for a week in case another user has a cookie problem.

**Comment by sebix** [comment]
I had that too: https://github.com/moinwiki/moin/issues/1788

I stand by my statement from that time:

> I wouldn't have expected a server error in such cases, to be honest.

Or, to be more precise: In my opinion, a user input (= a cookie) must not trigger _any_ exception on the server.
