### ISSUE TITLE
import19: UnboundLocalError: local variable 'editlog_data' referenced before assignment

### ISSUE THREAD

**Issue by diepes** [moinwiki/moin#1824]
while trying moin2 through pip 

```
moin --version
Python 3.9.6
Flask 3.1.0
Werkzeug 3.1.3
```

 converting/importing files from moin19 got the error below, the import continued after this 

```
2024-12-28 00:57:35,737 ERROR moin.cli.migration.moin19.import19:386 PageRevision 'ScubaDiving' '00000023' raised exception:
Traceback (most recent call last):
  File "/moin2/lib/python3.9/site-packages/moin/cli/migration/moin19/import19.py", line 377, in iter_revisions
    page_rev = PageRevision(self, revno, os.path.join(revisionspath, fname), self.target_namespace)
  File "/moin2/lib/python3.9/site-packages/moin/cli/migration/moin19/import19.py", line 460, in __init__
    meta.update(editlog_data)
UnboundLocalError: local variable 'editlog_data' referenced before assignment
```

**Comment by UlrichB22** [comment]
This seems to be related to 
https://github.com/moinwiki/moin/blob/8267f533fca6f5845ee467f012f1f9e2f5a18308/src/moin/cli/migration/moin19/import19.py#L449-L458

An else branch with a custom exception is missing there. Did you get the message "Missing edit log data: name = {item_name}, revision = {revno}" from line 452 before the traceback in the log? There seems to be an inconsistency between the "edit-log" file and the revision files in your moin1.9 data. I will add an exception message for this case, but it won't change the resulting moin2 wiki data.
