### ISSUE TITLE
url/+feed/atom gives BuildError

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#411]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/411) by kumar rishabh (Bitbucket: [hellboy2k8](https://bitbucket.org/hellboy2k8), GitHub: Unknown).**

----------------------------------------

```
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0/MoinMoin/apps/feed/views.py", line 102, in atom
url=url_for_item(name, rev=this_revid, _external=True),
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0/MoinMoin/util/interwiki.py", line 78, in url_for_item
url = url_for(endpoint, item_name=item_name, rev=rev, _external=_external)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
return appctx.app.handle_url_build_error(error, endpoint, values)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
reraise(exc_type, exc_value, tb)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
force_external=external)
File "/home/hellboy2k8/Documents/moinmoin/moin-2.0-venv-python/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
raise BuildError(endpoint, values, method)
BuildError: (u'frontend.show_item', {'rev': u'ff111346fbe9422795c2050ebde6bbb2'}, None)


```

**Comment by sblondon** [comment]
The code uses `feedgen` to generate Atom and runs only python3.
So, perhaps, this bug report is obsolete and can be closed.

**Comment by RogerHaase** [comment]
Saw this error a couple of days ago, but was unable to reproduce it while writing #1015. Agree it was fixed by #1013.

**Comment by RogerHaase** [comment]
Was able to reproduce error on freshly loaded sample wiki and again with same fresh wiki after one test update.

werkzeug.routing.BuildError: Could not build url for endpoint 'frontend.show_item' with values ['rev']. Did you forget to specify values ['item_name']?

Traceback (most recent call last)
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2464, in __call__
return self.wsgi_app(environ, start_response)
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2450, in wsgi_app
response = self.handle_exception(e)
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1867, in handle_exception
reraise(exc_type, exc_value, tb)
File "c:\git\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
rv = self.handle_user_exception(e)
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "c:\git\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "c:\git\moin\src\moin\apps\feed\views.py", line 104, in atom
feed_entry.id(url_for_item(name, rev=this_revid, _external=True))
File "c:\git\moin\src\moin\utils\interwiki.py", line 76, in url_for_item
url = url_for(endpoint, item_name=item_name, rev=rev, _external=_external)
File "c:\git\moin-venv-python\lib\site-packages\flask\helpers.py", line 370, in url_for
return appctx.app.handle_url_build_error(error, endpoint, values)
File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
reraise(exc_type, exc_value, tb)
File "c:\git\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
raise value
File "c:\git\moin-venv-python\lib\site-packages\flask\helpers.py", line 358, in url_for
endpoint, values, method=method, force_external=external
File "c:\git\moin-venv-python\lib\site-packages\werkzeug\routing.py", line 2020, in build
raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'frontend.show_item' with values ['rev']. Did you forget to specify values ['item_name']?

**Comment by UlrichB22** [comment]
Tested PR #1417 with a fresh instance initialized with `moin create-instance --full` and some manually changed items.

Following things have been changed with this fix:
- usage of fqname.fullname instead of name to support namespaces
- added debug logging
- moved content from summary to content section
- marked content as html, it was displayed as html source-code in feed-readers before

I didn't see any of those BuildErrors mentioned above while testing.
