### ISSUE TITLE
_modify_index via whoosh cannot handle more than one update at a given time.

### ISSUE THREAD

**Issue by ThomasWaldmann** [moinwiki/moin#479]
**[Original report](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/479) by johnyoon (Bitbucket: [johnyoon](https://bitbucket.org/johnyoon), GitHub: [johnyoon](https://github.com/johnyoon)).**

----------------------------------------

I have experimented with MpWriter (Multiprocessing) and BufferedWriter, and the latter works. The system I ran experimented is 4 core, 60GB, 320GB SSD (900/3600 IOPS), so that the hardware is not the bottleneck. I have also tried various parameters for uwsgi.

This is currently how it is in `./MoinMoin/storage/middleware/indexing.py`
```
#!/python
 def _modify_index(self, index, schema, wikiname, revids, mode='add', procs=1, limitmb=256):
     """
     modify index contents - add, update, delete the indexed documents for all given revids

     Note: mode == 'add' is faster but you need to make sure to not create duplicate
           documents in the index.
     """
     with index.writer(procs=procs, limitmb=limitmb) as writer:
         for backend_name, revid in revids:
             if mode in ['add', 'update', ]:
                 meta, data = self.backend.retrieve(backend_name, revid)
                 content = convert_to_indexable(meta, data, is_new=False)
```

This causes Exception for any parallel update request:

```
#!/bash
Traceback (most recent call last):
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_req
    rv = self.handle_user_exception(e)
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_excep
    reraise(exc_type, exc_value, tb)
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_req
    rv = self.dispatch_request()
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/www/moin/MoinMoin/apps/frontend/views.py", line 636, in modify_item
    return item.do_modify()
  File "/srv/www/moin/MoinMoin/items/__init__.py", line 876, in do_modify
    self.modify(meta, data, comment, contenttype_guessed, **{CONTENTTYPE: contenttype_qs})
  File "/srv/www/moin/MoinMoin/items/__init__.py", line 493, in modify
    return self._save(meta, data, contenttype_guessed=contenttype_guessed, comment=comment)
  File "/srv/www/moin/MoinMoin/items/__init__.py", line 635, in _save
    return_rev=True,
  File "/srv/www/moin/MoinMoin/storage/middleware/protecting.py", line 314, in store_revision
    rev = self.item.store_revision(meta, data, overwrite=overwrite, return_rev=return_rev, fqname=fqname, **kw)
  File "/srv/www/moin/MoinMoin/storage/middleware/indexing.py", line 1133, in store_revision
    self.indexer.index_revision(meta, content, backend_name)
  File "/srv/www/moin/MoinMoin/storage/middleware/indexing.py", line 496, in index_revision
    writer = self.ix[ALL_REVS].writer()
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/whoosh/index.py", line 464, in writer
    return SegmentWriter(self, **kwargs)
  File "/srv/www/moin-venv-python/local/lib/python2.7/site-packages/whoosh/writing.py", line 502, in __init__
    raise LockError
LockError
```

Increasing `proc=1` to some higher value will make Whoosh to use MpWriter internally, but it did not fix the problem, but `BufferedWriter` did fix the problem.

```
#!/bash
 writer = BufferedWriter(index, period=120, limit=40)
 for backend_name, revid in revids:
```

but before I want to make the change, I want to confirm that this is a proper fix.
This does not fix the parallel modify problem. After this fix, I still ran into concurrency problem with the `searcher()`

**Comment by RogerHaase** [comment]
This problem can be reproduced with Locust, see /contrib/loadtesting/locust/locustfile.py. Running with a 2 user simulation, there is a traceback in register:

    Traceback (most recent call last):
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2309, in __call__
        return self.wsgi_app(environ, start_response)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2295, in wsgi_app
        response = self.handle_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1741, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
        response = self.full_dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
        rv = self.dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "c:\git\moin\src\moin\apps\frontend\views.py", line 1552, in register
        msg = user.create_user(**user_kwargs)
      File "c:\git\moin\src\moin\user.py", line 110, in create_user
        theuser.save()
      File "c:\git\moin\src\moin\user.py", line 521, in save
        self.profile.save(force=force)
      File "c:\git\moin\src\moin\user.py", line 290, in save
        item.store_revision(self._meta, BytesIO(b''), overwrite=True)
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 1144, in store_revision
        self.indexer.index_revision(meta, content, backend_name)
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 505, in index_revision
        writer = self.ix[ALL_REVS].writer()
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\index.py", line 464, in writer
        return SegmentWriter(self, **kwargs)
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\writing.py", line 515, in __init__
        raise LockError
    LockError

And here is traceback doing an item modify as described in original report:

    Traceback (most recent call last):
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2309, in __call__
        return self.wsgi_app(environ, start_response)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2295, in wsgi_app
        response = self.handle_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1741, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
        response = self.full_dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
        rv = self.dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "c:\git\moin\src\moin\apps\frontend\views.py", line 719, in modify_item
        ret = item.do_modify()
      File "c:\git\moin\src\moin\items\__init__.py", line 1041, in do_modify
        self.modify(meta, data, comment, contenttype_guessed, **{CONTENTTYPE: contenttype_qs})
      File "c:\git\moin\src\moin\items\__init__.py", line 567, in modify
        return self._save(meta, data, contenttype_guessed=contenttype_guessed, comment=comment)
      File "c:\git\moin\src\moin\items\__init__.py", line 719, in _save
        return_rev=True,
      File "c:\git\moin\src\moin\storage\middleware\protecting.py", line 315, in store_revision
        rev = self.item.store_revision(meta, data, overwrite=overwrite, return_rev=return_rev, fqname=fqname, **kw)
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 1144, in store_revision
        self.indexer.index_revision(meta, content, backend_name)
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 512, in index_revision
        writer = self.ix[LATEST_REVS].writer()
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\index.py", line 464, in writer
        return SegmentWriter(self, **kwargs)
      File "c:\git\moin-venv-python\lib\site-packages\whoosh\writing.py", line 515, in __init__
        raise LockError
    LockError

**Comment by RogerHaase** [comment]
I can reproduce this traceback using Locust on Windows (quad core, 12 GB) and on a remote website (WebFaction) running CentOS, but cannot reproduce the traceback on Ubuntu running on an old AMD dual core 2.9 processor with 2 GB of memory. The failures occur quickly on Windows/CentOS with 3 locusts, takes a minute or 2 with 2 locusts. Could not reproduce the failure on Ubuntu with 20 locusts after 5 minutes.
