### ISSUE TITLE
No user feedback when uploading invalid html files with Global Index

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#760]
If a user uploads poorly formatted html (say some of the files in /templates/), then there may be tracebacks in the console log that are generated during the indexing process. The index process may also generate flash messages because of unsupported html tags.

During and after the upload process the user receives no negative feedback, instead the flash messages will appear on the next transaction, possibly completely out of context.  If multiple files are uploaded there is no indication of which file caused the error.

Probably difficult, but the user should receive better and more immediate feedback.

Sample traceback follows. There is no need to solve the error, rather this and similar tracebacks should generate a flash message that the user sees immediately.

        2018-11-08 13:54:13,538 ERROR moin.storage.middleware.indexing:267 Exception happened in conversion of item u'modify.htm
        l' rev new contenttype text/html:
        Traceback (most recent call last):
          File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 247, in convert_to_indexable
            doc = input_conv(rev, input_contenttype)
          File "c:\git\moin\src\moin\converters\html_in.py", line 150, in __call__
            element = self.do_children(html_tree)
          File "c:\git\moin\src\moin\converters\html_in.py", line 165, in do_children
            r = self.visit(child)
          File "c:\git\moin\src\moin\converters\html_in.py", line 227, in visit
            return method(element)
          File "c:\git\moin\src\moin\converters\html_in.py", line 246, in visit_xhtml
            return self.new_copy(self.simple_tags[element.tag.name], element, attrib={})
          File "c:\git\moin\src\moin\converters\html_in.py", line 190, in new_copy
            children = self.do_children(element)
          File "c:\git\moin\src\moin\converters\html_in.py", line 165, in do_children
            r = self.visit(child)
          File "c:\git\moin\src\moin\converters\html_in.py", line 227, in visit
            return method(element)
          File "c:\git\moin\src\moin\converters\html_in.py", line 242, in visit_xhtml
            return self.new_copy_symmetric(element, attrib={})
          File "c:\git\moin\src\moin\converters\html_in.py", line 201, in new_copy_symmetric
            return self.new_copy(tag, element, attrib)
          File "c:\git\moin\src\moin\converters\html_in.py", line 190, in new_copy
            children = self.do_children(element)
          File "c:\git\moin\src\moin\converters\html_in.py", line 165, in do_children
            r = self.visit(child)
          File "c:\git\moin\src\moin\converters\html_in.py", line 227, in visit
            return method(element)
          File "c:\git\moin\src\moin\converters\html_in.py", line 264, in visit_xhtml
            return method(element)
          File "c:\git\moin\src\moin\converters\html_in.py", line 518, in visit_xhtml_dl
            if child.tag.name == 'dt' or child.tag.name == 'dd':
        AttributeError: 'unicode' object has no attribute 'tag'

**Comment by RogerHaase** [comment]
dup of #869.
