### ISSUE TITLE
Traceback when viewing any markdown item - ImportError: Failed loading extension "fenced_code"

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#788]
This happens here: https://digitalrockart.org/moin/markdown 

Works OK on other installations using built-in server on Windows and Ubuntu. The failing installation is using Apache serving moin 2. Have tried deleting virtualenv and reinstalling, but the problem persists on any markdown item.

Problem started after pulling changes upgrading to markdown 3.0 / 3.0.1.  iirc I had to delete the virtualenv on both Windows and Ubuntu to get a working version of markdown 3.0, but doing same has no affect here.

    Traceback (most recent call last):
     File "/home/rockart/webapps/web/moin/src/moin/items/content.py", line 255, in _render_data
        doc = self.internal_representation()
      File "/home/rockart/webapps/web/moin/src/moin/utils/clock.py", line 62, in wrapper
        retval = f(*args, **kw)
      File "/home/rockart/webapps/web/moin/src/moin/items/content.py", line 206, in internal_representation
        input_conv = reg.get(Type(self.contenttype), type_moin_document)
      File "/home/rockart/webapps/web/moin/src/moin/utils/registry.py", line 46, in get
        conv = entry(*args, **kw)
      File "/home/rockart/webapps/web/moin/src/moin/converters/__init__.py", line 37, in __call__
        return self.factory(type_input, type_output, **kw)
      File "/home/rockart/webapps/web/moin/src/moin/converters/markdown_in.py", line 544, in _factory
        return cls()
      File "/home/rockart/webapps/web/moin/src/moin/converters/markdown_in.py", line 539, in __init__
        CodeHiliteExtension(guess_lang=False),
      File "/home/rockart/webapps/web/moin-venv-python2.7/lib/python2.7/site-packages/markdown/core.py", line 100, in __init__
        configs=kwargs.get('extension_configs', {}))
      File "/home/rockart/webapps/web/moin-venv-python2.7/lib/python2.7/site-packages/markdown/core.py", line 128, in registerExtensions
        ext._extendMarkdown(self)
      File "/home/rockart/webapps/web/moin-venv-python2.7/lib/python2.7/site-packages/markdown/extensions/__init__.py", line 79, in _extendMarkdown
        self.extendMarkdown(md)
      File "/home/rockart/webapps/web/moin-venv-python2.7/lib/python2.7/site-packages/markdown/extensions/extra.py", line 58, in extendMarkdown
        md.registerExtensions(extensions, self.config)
      File "/home/rockart/webapps/web/moin-venv-python2.7/lib/python2.7/site-packages/markdown/core.py", line 126, in registerExtensions
        ext = self.build_extension(ext, configs.get(ext, {}))
      File "/home/rockart/webapps/web/moin-venv-python2.7/lib/python2.7/site-packages/markdown/core.py", line 166, in build_extension
        module = importlib.import_module(ext_name)
      File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
    ImportError: Failed loading extension "fenced_code".

**Comment by RogerHaase** [comment]
User error. Was running with an invalid httpd.conf file for years. Fixed after correcting use of WSGIDaemonProcess per bottom of http://blog.dscpl.com.au/2014/09/using-python-virtual-environments-with.html.
