### ISSUE TITLE
traceback when modified ACL denies read access to current user

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#792]
When a user creates or modifies an item and changes the item's ACL rules to deny read access for himself then there is a traceback:

    Traceback (most recent call last):
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2309, in __call__
        return self.wsgi_app(environ, start_response)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2295, in wsgi_app
        response = self.handle_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1741, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
        response = self.full_dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
        rv = self.dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "c:\git\moin\src\moin\apps\frontend\views.py", line 726, in modify_item
        ret = item.do_modify()
      File "c:\git\moin\src\moin\items\__init__.py", line 1007, in do_modify
        self.modify(meta, data, comment, contenttype_guessed, **{CONTENTTYPE: contenttype_qs})
      File "c:\git\moin\src\moin\items\__init__.py", line 565, in modify
        return self._save(meta, data, contenttype_guessed=contenttype_guessed, comment=comment)
      File "c:\git\moin\src\moin\items\__init__.py", line 719, in _save
        item_modified.send(app, fqname=self.fqname, action=action)
      File "c:\git\moin-venv-python\lib\site-packages\blinker\base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "c:\git\moin\src\moin\utils\notifications.py", line 223, in send_notifications
        meta_diff = notification.get_meta_diff()
      File "c:\git\moin\src\moin\utils\notifications.py", line 127, in get_meta_diff
        new_meta = dict(self.revs[0].meta)
    IndexError: list index out of range

As the error is in notifications.py, the bug may only occur if email is configured.

**Comment by RogerHaase** [comment]
There are 3 approaches to the problem.

1. If an editor attempts to change ACLs in a way that will prevent self from reading the item. flag it as a error that requires correction before the item can be saved.

2. Create the diffs earlier in the save process before the ACLs are changed.

3. Add a new search method in storage/middleware/protecting.py that will return revisions without checking current user's read permission. This is safe because the diffs will not be emailed to the current author nor any subscriber that does not have read authority for the newly saved item.

**Comment by RogerHaase** [comment]
Fix reverted. Caused new problem: when a user created a new home page, the item was saved correctly and then the user received the Access Denied view. Doing a refresh showed new home page.

**Comment by RogerHaase** [comment]
See #944 as near duplicate.

There is a 4th approach: instead of reloading the last 2 revisions to create the diff for notification, just pass the data that is already loaded into memory to send_notifications. Must verify this will work for modify, delete, destroy, convert, and JFU_server.
