### ISSUE TITLE
Traceback on pythonanywhere.com when viewing item with non-ascii name

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#833]
Moin2 was installed on free version of pythonanywhere.com following guide in /contrib/pythonanywhere/.

When viewing an item with a non-ascii name there is a traceback. Failing URL:

    http://moinmoin2.pythonanywhere.com/AjudaNaFormata%C3%A7%C3%A3o

A workaround has been applied to /signalling/log.py to comment out one line. 

    diff --git a/src/moin/signalling/log.py b/src/moin/signalling/log.py
    index d180410..cc7ef9f 100644
    --- a/src/moin/signalling/log.py
    +++ b/src/moin/signalling/log.py
    @@ -16,7 +16,7 @@ logging = log.getLogger(__name__)
     @item_displayed.connect_via(ANY)
     def log_item_displayed(app, fqname):
         wiki_name = app.cfg.interwikiname
    -    logging.info(u"item {0}:{1} displayed".format(wiki_name, unicode(fqname)))
    +    # logging.info(u"item {0}:{1} displayed".format(wiki_name, unicode(fqname)))
     
     
     @item_modified.connect_via(ANY)

The website seems to function OK after workaround was applied. Note error log shows an occasional "IOError: write error" for some unknown reason.

The traceback before workaround was applied:

    2019-05-30 14:33:05,975: timer init(0): 1.08ms
    2019-05-30 14:33:05,992: 'ascii' codec can't encode characters in position 30-31: ordinal not in range(128)
    Traceback (most recent call last):
      File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 2311, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1737, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1818, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/MoinMoin2/moin/src/moin/apps/frontend/views.py", line 496, in show_item
        fqname=fqname)
      File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/blinker/base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "/home/MoinMoin2/moin/src/moin/signalling/log.py", line 19, in log_item_displayed
        logging.info(u"item {0}:{1} displayed".format(wiki_name, unicode(fqname)))
      File "/usr/lib/python2.7/logging/__init__.py", line 1167, in info
        self._log(INFO, msg, args, **kwargs)
      File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
        self.handle(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
        self.callHandlers(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
        hdlr.handle(record)
      File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
        self.emit(record)
      File "/bin/user_wsgi_wrapper.py", line 110, in emit
        format_with_millis(datetime.now()), self.format(record)
    UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-31: ordinal not in range(128)
    2019-05-30 14:33:05,995: timer total(0): 21.21ms
    2019-05-30 14:33:05,995: Error running WSGI application
    2019-05-30 14:33:05,995: UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-29: ordinal not in range(128)
    2019-05-30 14:33:05,996:   File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 2328, in __call__
    2019-05-30 14:33:05,996:     return self.wsgi_app(environ, start_response)
    2019-05-30 14:33:05,996: 
    2019-05-30 14:33:05,996:   File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 2314, in wsgi_app
    2019-05-30 14:33:05,997:     response = self.handle_exception(e)
    2019-05-30 14:33:05,997: 
    2019-05-30 14:33:05,997:   File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1764, in handle_exception
    2019-05-30 14:33:05,997:     self.log_exception((exc_type, exc_value, tb))
    2019-05-30 14:33:05,997: 
    2019-05-30 14:33:05,998:   File "/home/MoinMoin2/moin-venv-python/local/lib/python2.7/site-packages/flask/app.py", line 1780, in log_exception
    2019-05-30 14:33:05,998:     ), exc_info=exc_info)
    2019-05-30 14:33:05,998: 
    2019-05-30 14:33:05,998:   File "/usr/lib/python2.7/logging/__init__.py", line 1193, in error
    2019-05-30 14:33:05,998:     self._log(ERROR, msg, args, **kwargs)
    2019-05-30 14:33:05,999: 
    2019-05-30 14:33:05,999:   File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    2019-05-30 14:33:05,999:     self.handle(record)
    2019-05-30 14:33:05,999: 
    2019-05-30 14:33:05,999:   File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    2019-05-30 14:33:06,000:     self.callHandlers(record)
    2019-05-30 14:33:06,000: 
    2019-05-30 14:33:06,000:   File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    2019-05-30 14:33:06,000:     hdlr.handle(record)
    2019-05-30 14:33:06,000: 
    2019-05-30 14:33:06,001:   File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    2019-05-30 14:33:06,001:     self.emit(record)
    2019-05-30 14:33:06,460: timer init(0): 0.87ms
    2019-05-30 14:33:06,461: item MyMoinMoin:favicon.ico displayed
    2019-05-30 14:33:06,616: timer navibar(0): 0.23ms
    2019-05-30 14:33:06,653: timer total(0): 193.94ms

**Comment by RogerHaase** [comment]
I should have waited a few more minutes... From pythonanywhere support:

    Hi,
    We had a bug in our wrapper code that was preventing Python 2 from 
    logging non-ascii through the logging module. I have fixed it and that 
    page is working now.
    Thanks
    Glenn

Workaround removed, everything seems to work.
