### ISSUE TITLE
Stacktrace when editing `Home`

### ISSUE THREAD

**Issue by kwatsen** [moinwiki/moin#871]
I admit that this might be user error, as I changed the `interwikiname` in `wikiconfig_editme.py`:

```
wikiconfig_editme.py:    interwikiname = u'MyWikiName'
```

Upon clicking "OK" on the `+modify/Home`, the below stacktrace occurs, and a HTTP 500 
(Internal Server Error) is returned.  However, manually reloading the Home page renders the change just fine.

FWIW, modifying any other page works fine. 

```
[pid: 67896|app: 0|req: 2175/2175] 10.0.4.6 () {52 vars in 1258 bytes} [Mon Aug  5 11:14:52 2019] GET /+modify/Home => generated 16048 bytes in 470 msecs (HTTP/1.1 200) 4 headers in 497 bytes (5 switches on core 0)
2019-08-05 11:15:03,650 INFO moin.utils.clock:45 timer init(0): 35.22ms
2019-08-05 11:15:04,442 INFO moin.signalling.log:25 item MyWikiName:Home modified
2019-08-05 11:15:05,430 ERROR moin.signalling.log:30 u'MyWikiNamel'
Traceback (most recent call last):
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/share/moin2/moin/src/moin/apps/frontend/views.py", line 720, in modify_item
    ret = item.do_modify()
  File "/usr/local/share/moin2/moin/src/moin/items/__init__.py", line 1115, in do_modify
    self.modify(meta, data, comment, contenttype_guessed, **{CONTENTTYPE: contenttype_qs})
  File "/usr/local/share/moin2/moin/src/moin/items/__init__.py", line 573, in modify
    return self._save(meta, data, contenttype_guessed=contenttype_guessed, comment=comment)
  File "/usr/local/share/moin2/moin/src/moin/items/__init__.py", line 727, in _save
    item_modified.send(app, fqname=newrev.fqname, action=action)
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/share/moin2/moin/src/moin/utils/notifications.py", line 230, in send_notifications
    txt_msg, html_msg = notification.render_templates(content_diff, meta_diff)
  File "/usr/local/share/moin2/moin/src/moin/utils/notifications.py", line 156, in render_templates
    domain = self.app.cfg.interwiki_map[self.app.cfg.interwikiname]
KeyError: u'MyWikiName'
2019-08-05 11:15:05,500 ERROR flask.app:1761 Exception on /+modify/Home [POST]
Traceback (most recent call last):
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/share/moin2/moin/src/moin/apps/frontend/views.py", line 720, in modify_item
    ret = item.do_modify()
  File "/usr/local/share/moin2/moin/src/moin/items/__init__.py", line 1115, in do_modify
    self.modify(meta, data, comment, contenttype_guessed, **{CONTENTTYPE: contenttype_qs})
  File "/usr/local/share/moin2/moin/src/moin/items/__init__.py", line 573, in modify
    return self._save(meta, data, contenttype_guessed=contenttype_guessed, comment=comment)
  File "/usr/local/share/moin2/moin/src/moin/items/__init__.py", line 727, in _save
    item_modified.send(app, fqname=newrev.fqname, action=action)
  File "/usr/local/share/moin2/moin-venv-python/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/share/moin2/moin/src/moin/utils/notifications.py", line 230, in send_notifications
    txt_msg, html_msg = notification.render_templates(content_diff, meta_diff)
  File "/usr/local/share/moin2/moin/src/moin/utils/notifications.py", line 156, in render_templates
    domain = self.app.cfg.interwiki_map[self.app.cfg.interwikiname]
KeyError: u'MyWikiName'
2019-08-05 11:15:05,503 INFO moin.utils.clock:45 timer total(0): 1888.12ms
[pid: 67896|app: 0|req: 2176/2176] 10.0.4.6 () {60 vars in 1441 bytes} [Mon Aug  5 11:15:03 2019] POST /+modify/Home => generated 290 bytes in 1893 msecs (HTTP/1.1 500) 2 headers in 83 bytes (2 switches on core 0)
```

**Comment by ThomasWaldmann** [comment]
Tried to reproduce with the current (python3) code from master branch.
I didn't get the traceback, but some stuff was obviously not working correctly (e.g. global index and history).

Guess this is due to a mismatch of the current wiki name and the index. I rebuilt the index using `./m index` and then it was back to normal.

**Comment by RogerHaase** [comment]
This should be written more clearly and retested, but iirc changing interwikiname, SECRET_KEY, or secrets requires that the index be rebuilt.

https://moin-20.readthedocs.io/en/latest/admin/install.html#next-steps

**Comment by RogerHaase** [comment]
Correction to above, changing the interwikiname on an existing wiki requires rebuilding the index. Not doing so will result in no items being found. No tracebacks noted. Changing SECRET_KEY or secrets did not require rebuilding the index. Could not reproduce the traceback.

Will add a comment to wikiconfig.py saying the index must be rebuilt if interwikiname is changed.
