### ISSUE TITLE
index broken for PDF

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#897]
If you upload a PDF file or do a ./m index on a wiki that has a PDF file, then a traceback is written to the console log.

    2019-08-11 14:38:21,272 ERROR moin.storage.middleware.indexing:291 Exception happened in conversion of item 'Equifax.pdf' rev 94686a0e087c4a468b841df26b898d69 contenttype application/pdf:
    Traceback (most recent call last):
      File "c:\git37\moin\src\moin\storage\middleware\indexing.py", line 263, in convert_to_indexable
        doc = conv(rev, input_contenttype)
      File "c:\git37\moin\src\moin\converters\pdf_in.py", line 62, in __call__
        device = UnicodeConverter(rsrcmgr, laparams=LAPARAMS)
      File "c:\git37\moin\src\moin\converters\pdf_in.py", line 45, in __init__
        showpageno=showpageno)
      File "C:\git37\moin-venv-python\lib\site-packages\pdfminer3\converter.py", line 185, in __init__
        PDFConverter.__init__(self, rsrcmgr, outfp, codec=codec, pageno=pageno, laparams=laparams)
      File "C:\git37\moin-venv-python\lib\site-packages\pdfminer3\converter.py", line 172, in __init__
        self.outfp.write("é")
    AttributeError: 'NoneType' object has no attribute 'write'

**Comment by ThomasWaldmann** [comment]
The way our code used `pdfminer` and overwrote some of its methods by subclassing is not good enough for `pdfminer3` (py3 compatible version).
