### ISSUE TITLE
import19 fails with py3 bytes vs. strings issue

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#921]
Converting Pages/Attachments...

    Traceback (most recent call last):
      File "c:\GIT\moin-venv-python\Scripts\moin-script.py", line 11, in <module>
        load_entry_point('moin', 'console_scripts', 'moin')()
      File "c:\git\moin\src\moin\scripts\__init__.py", line 59, in main
        return manager.run(default_command=default_command)
      File "c:\git\moin-venv-python\lib\site-packages\flask_script\__init__.py", line 417, in run
        result = self.handle(argv[0], argv[1:])
      File "c:\git\moin-venv-python\lib\site-packages\flask_script\__init__.py", line 386, in handle
        res = handle(*args, **config)
      File "c:\git\moin-venv-python\lib\site-packages\flask_script\commands.py", line 216, in __call__
        return self.run(*args, **kwargs)
      File "c:\git\moin\src\moin\scripts\migration\moin19\import19.py", line 105, in run
        for rev in PageBackend(data_dir, deleted_mode=DELETED_MODE_KILL, default_markup='wiki'):
      File "c:\git\moin\src\moin\scripts\migration\moin19\import19.py", line 206, in __iter__
        itemname = unquoteWikiname(f)
      File "c:\git\moin\src\moin\scripts\migration\moin19\_utils19.py", line 135, in unquoteWikiname
        for needle in QUOTED.finditer(filename):
    TypeError: <moin.scripts.migration.moin19.import19.ImportMoin19 object at 0x0000029A13F49A08>: cannot use a string pattern on a bytes-like object

**Comment by ingoha** [comment]
Facing the same issue - will try your patch...

**Comment by ThomasWaldmann** [comment]
Hmm, is this a change that did not end up in a pull request?

**Comment by ingoha** [comment]
Seems so :-/ However, for me it fixes the issue - so +1

**Comment by ingoha** [comment]
Should I open a PR?

**Comment by ingoha** [comment]
@ThomasWaldmann Is it this PR: https://github.com/moinwiki/moin/pull/922?

**Comment by ThomasWaldmann** [comment]
Right. I started reviewing this a while ago, but never finished.

Reviewed again and there are only 2 small things left to clear / to do.

**Comment by ingoha** [comment]
Can I do anything to get the PR merged faster? I have another fix pending for `import19.py` which is based on the version of @RogerHaase. Without his patch, the import script fails epicly when encountering the first Umlaut...

**Comment by ThomasWaldmann** [comment]
I've merged it "as is" and made a new issue about the stuff found in review.

**Comment by ingoha** [comment]
Cool, thanks :-)
