### ISSUE TITLE
import19 fails processing .odb attachment

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#923]
2019-09-24 09:14:16,589 ERROR moin.storage.middleware.indexing:287 
    Exception happened in conversion of item 'RogerHaase/PrivatePages/AASCertification.odb' 
    rev 5f61e60f40d0421c93dadee7d4986884 contenttype application/vnd.oasis.opendocument.database:

    Traceback (most recent call last):
      File "c:\git\moin\src\moin\storage\middleware\indexing.py", line 259, in convert_to_indexable
        doc = conv(rev, input_contenttype)
      File "c:\git\moin\src\moin\converters\opendocument_in.py", line 29, in __call__
        data = zf.read("content.xml")
      File "C:\Python37\Lib\zipfile.py", line 1431, in read
        with self.open(name, "r", pwd) as fp:
      File "C:\Python37\Lib\zipfile.py", line 1483, in open
        self._fpclose, self._lock, lambda: self._writing)
      File "C:\Python37\Lib\zipfile.py", line 722, in __init__
        self.seekable = file.seekable
    AttributeError: 'PseudoRev' object has no attribute 'seekable'

**Comment by UlrichB22** [comment]
IMO it is sufficient to issue a warning message. Office documents can only be added by import19 from attachments. There is no content_type for new office items in moin2 AFAIK.
