### ISSUE TITLE
traceback when user reverts item with ACLs denying read access

### ISSUE THREAD

**Issue by RogerHaase** [moinwiki/moin#944]
The traceback is similar to #792 

While logged in, create an item giving all ACL rights to Known users and denying read rights to All users.

Modify the item, creating a second revision, and changing the ACLs to the default (None).

Logout.

As a logged out user, view the history of the above, click the revert link for the first revision (with ACLs denying read access for this logged out user). The result is a traceback:

    2020-01-18 10:28:16,676 INFO werkzeug:122 127.0.0.1 "POST /+revert/+d328e67224c846b0b46e86532fb0d105/x HTTP/1.1" 500 -
    Traceback (most recent call last):
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2463, in __call__
        return self.wsgi_app(environ, start_response)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2449, in wsgi_app
        response = self.handle_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1866, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
        response = self.full_dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "c:\git\moin-venv-python\lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "c:\git\moin-venv-python\lib\site-packages\flask\app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "c:\git\moin\src\moin\apps\frontend\views.py", line 801, in revert_item
        item.revert(form['comment'])
      File "c:\git\moin\src\moin\items\__init__.py", line 546, in revert
        return self._save(self.meta, self.content.data, action=ACTION_REVERT, comment=comment)
      File "c:\git\moin\src\moin\items\__init__.py", line 727, in _save
        item_modified.send(app, fqname=newrev.fqname, action=action)
      File "c:\git\moin-venv-python\lib\site-packages\blinker\base.py", line 267, in send
        for receiver in self.receivers_for(sender)]
      File "c:\git\moin-venv-python\lib\site-packages\blinker\base.py", line 267, in <listcomp>
        for receiver in self.receivers_for(sender)]
      File "c:\git\moin\src\moin\utils\notifications.py", line 221, in send_notifications
        meta_diff = notification.get_meta_diff()
      File "c:\git\moin\src\moin\utils\notifications.py", line 127, in get_meta_diff
        new_meta = dict(self.revs[0].meta)
    IndexError: list index out of range

Currently, ACL checks are made by item fqname; there is no code to check ACLs by item revision. If a user attempts to view an item's history, he is blocked if read permission is denied based on the current ACLs. If read permission is allowed, then the entire item history is presented, and the user may view older revisions (by clicking on the Show links) even if the ACLs stored in metadata for the older revision deny read access.

Based upon current code:

* it is a bug for the revert action to copy ACLs from an older revision, the current ACLs must be  copied to the metadata of the new revision
* https://moin-20.readthedocs.io/en/latest/admin/configure.html#authorization should be updated to state ACLs are per item not item revision

**Comment by ThomasWaldmann** [comment]
I didn't look at the code yet, but I have doubts whether current ACLs should overwrite the new (reverted) revisions ACLs. That means that users can then view content which they were not previously allowed to see.

**Comment by RogerHaase** [comment]
Ok, will say bug is in notifications.py then. Assuming that you realize that if ACLs for an item are loosened, then That means that (some affected) users can then view content (from prior revisions) which they were not previously allowed to see.

Only way around the above is to implement ACLs by revision for Item History, maybe others.

**Comment by ThomasWaldmann** [comment]
Maybe there could be a try/except in the loop generating the history page and in the permissions denied case, it would just display some placeholder code (or nothing) instead of the entry.

**Comment by RogerHaase** [comment]
closed as dup of #792
